<?php
// Register TV Shows Post Type
	$labels = array(
		'name'                  => 'TV Shows',
		'singular_name'         => 'TV Show',
		'menu_name'             => 'TV Shows',
		'name_admin_bar'        => 'TV Show',
		'all_items'             => 'Alle shows',
		'add_new_item'          => 'Nieuwe show',
		'add_new'               => 'Voeg show toe',
		'new_item'              => 'Nieuwe show',
		'edit_item'             => 'Bewerkt show',
		'update_item'           => 'Update show',
		'view_item'             => 'Bekijk show',
		'view_items'            => 'Bekijk shows',
		'search_items'          => 'Zoek shows',
	);
	$args = array(
		'label'                 => 'TV Shows',
		'description'           => 'Shows die op TV worden uitgezonden',
		'labels'                => $labels,
		'supports'              => [ 'title', 'editor', 'thumbnail' ],
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'             => 'dashicons-welcome-view-site',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'post',
		'show_in_rest'          => true,
		'rest_base'             => 'tv',
		'rewrite'               => [ 'slug' => 'tv', 'with_front' => true ],
	);
	register_post_type( 'tvshows', $args );
